# Derived from official mysql image (our base image)
FROM mysql:5.7
# Add a database with a given name
ENV MYSQL_DATABASE test_database
# Sets the root password
ENV MYSQL_ROOT_PASSWORD root
# Create an extra user for development
ENV MYSQL_USER test
ENV MYSQL_PASSWORD test
