version: '3.3'
services:
  db:
    container_name: test-framework-mysql
    restart: always
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
